### PR TITLE
Config overrides api

### LINKED ISSUE #82: API don't respect `extend`
When reporting a bug, please include:

  * A little info about your environment
    * npm-package-json-lint version 3.0.0
    * npm version 6.0.0
    * node version 10.0.0
  * The output from npm-package-json-lint
   Output error only which in configuration list without rules in extend.
  * What you expected to happen
    Respect `extends` in api
  * The steps to reproduce the problem
    ```js
    new NpmPackageJsonLint().lint(
      packageJsonData, 
      ThisVariableAcceptOnlyArrayOfRulesButShouldAcceptConfigAndRespectExtends
    );
    ```

In `2` version all works good and as expected. Thanks!

### LINKED ISSUE #96: Support overrides
It would be great to have support for an `overrides` field in the config file, just like `ESLint` has. This could be especially useful for monorepos.

```json
{
  "overrides": {
    "files": ["./package.json", "./packages/package1/package.json"],
    "rules": {
      "require-homepage": "off"
    }
  }
}
```

Any plans to support this? Ready to help.

### PR DESCRIPTION
**Pull request by tclindner**
**Description of change**
Add logic to apply overrides  - Closes #96
Add cosmicconfig and switch to globby
Add new utils for ignore and file list
Add error handling to config
Add typedef to LintIssue
Add new linter and results helper
Add tests for utils
Tests for new linter
Add test for absolute paths
Add tests for overrides and extends
Add ignore support to cli reporter
Update api now that CLIEngine is no longer exported
Update Reporter.js
Add initial version of transformer
Add config tests
Update CHANGELOG.md
Closes #82

**Checklist**

  - [x] Unit tests have been added

### CODE REVIEW

**Comment by simison** [comment]
This is very cool! Would it be possible to get a new NPM release with this feature? :-)

**Comment by tclindner** [comment]
Definitely! Sorry for the delay 🙈

File: src/config/applyOverrides.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
+const debug = require('debug')('npm-package-json-lint:applyOverrides');
+const path = require('path');
+const globby = require('globby');
+
+/**
+ * Applies values from the 'overrides' field in a configuration file.
+ * @param {string} cwd       The current working directory.
+ * @param {Object} filePath  The file path of the file being linted.
```
Comment (simison) [inline src/config/applyOverrides.js]: @tclindner is this working as intended for you? I'm seeing the path of the config file as `filePath` instead of file being linted. Therefore `filePath === globbedFilePath` is never truthy and overrides don't work.

Note how path gets pulled from config object here before passed to `applyOverrides`:

https://github.com/tclindner/npm-package-json-lint/pull/123/files#diff-4c88ce73413b52beff7db767b94bd2f4R11

Comment (tclindner) [reply src/config/applyOverrides.js]: Hey @simison - it seems to be working for my basic setup. What does your setup look like? We can try to get a patch in.

Comment (simison) [reply src/config/applyOverrides.js]: Heh, well you just got me to doubt myself and if I was testing thoroughly enough! 😅 

Here's the config I'm working on https://github.com/Automattic/wp-calypso/pull/36534

No worries if you don't have time, I can also dig deeper into this.

Comment (tclindner) [reply src/config/applyOverrides.js]: Thank you, @simison! I think I have a fix ready. Please give v4.0.1 a shot and let me know if it resolves your issue. Thanks again for reporting it 👍

Comment (simison) [reply src/config/applyOverrides.js]: Yasss, that worked fantastically! Thank you!
